export {default as projectRouter} from './routes/project.routes'
export {default as userRouter} from './routes/user.routes'
export {default as spotRouter} from './routes/spot.routes'
export {default as placeRouter} from './routes/place.routes'
export {default as authRouter} from './routes/auth.routes'
